var game = new Phaser.Game(800, 600, Phaser.AUTO);
//game.state.add('Load', boil.Load);
//game.state.add('Menu', boil.Menu);
game.state.add('Play', boil.Play);
game.state.add('Level2', boil.Level2);
game.state.add('Level3', boil.Level3);
game.state.add('Level4', boil.Level4);
game.state.add('Level5', boil.Level5);
game.state.add('win', boil.win);
game.state.add('GameOver', boil.GameOver);
game.state.start('Play'); 
